spring:
  application.name: es-student-service

  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    url: jdbc:postgresql://edusystem-database-1.clmxt4f8zcur.us-west-2.rds.amazonaws.com:5432/es_student
    username: edusystem
    password: password
    driver-class-name: org.postgresql.Driver
    schema: classpath:/schema-postgres.sql
    initialization-mode: never
    platform: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env"]