CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE STUDENT (
   ID BIGINT PRIMARY KEY,
   CLASS_ID BIGINT NOT NULL,
   FIRST_NAME VARCHAR(256) NOT NULL,
   LAST_NAME VARCHAR(256) NOT NULL
);
COMMIT;